config/routes.rb
Quizapp::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'users/list' => 'users#index'
    get 'users/report' => 'users#report'
    get 'users/:id' => 'users#show'
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users

  get 'trainers/logo' => 'trainers#logo', :via => :get
  resources :trainers
  get 'trainers/:id/crop' => 'trainers#crop'
  post 'trainers/:id/cropped_image' => 'trainers#cropped_image'
  get 'trainers/:id/remove_logo' => 'trainers#remove_logo'

  resources :documents, only: %i[index new create destroy]

  get 'documents/index'

  get 'documents/new'

  get 'documents/create'

  get 'documents/destroy'

  root 'home#page'

  get 'home/page'

  get 'home/support_contact'

  get 'home/about'

  get 'questions/list'
  get 'questions/setting' => 'questions#setting', :via => :get
  post 'questions/save_setting' => 'questions#save_setting', :via => :post
  resources :questions

  get 'quiz/index'

  post 'quiz/start'

  get 'quiz/question'

  post 'quiz/question'

  post 'quiz/answer'

  get 'quiz/result'

  post 'choices/create'

  post 'choices/destroy'

  post 'reporter/create'

  get 'reporter/index'

  get 'reporter/check'

  get 'reporter/list'

  post 'reporter/save'

  resource :candidates

  get 'candidates/synchronize'

  post 'candidates/refresh'

end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :choices

  def answer
    uncorrect
    choices.select(&:correct)[0]
  end

  def uncorrect
    choices.each { |c| c.correct = false }
  end

  def answer=(choice)
    answer.correct = false unless answer.nil?

    if choices.include? choice
    else
      choices << choice
    end
    choice.correct = true
  end
end

app/controllers/questions_controller.rb
#--
# cyber_quiz
#
# A  Ruby application for enterprise online quiz management solution
#
# Developed by Yang Li, Kainan Zhang. Creative Common License
#
#++

class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.xml
  before_action :authenticate_user!

  def index; end

  def list
    @questions = Question.where(category: params[:category])
    if @questions.size > 1
      #  @questions = @questions.to_a.sort {|a,b| a.text <=> b.text}
    end
    respond_to do |format|
      format.html
      format.xml  { render xml: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.xml
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render xml: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.xml
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render xml: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.xml
  def create
    @question = Question.new(category: params[:question][:category].to_s, text: params[:question][:text].to_s)

    respond_to do |format|
      if @question.save
        format.html { redirect_to(@question, notice: 'Question was successfully created.') }
        format.xml  { render xml: @question, status: :created, location: @question }
      else
        format.html { render action: 'new' }
        format.xml  { render xml: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.xml
  def update
    #    render plain: params.inspect
    @question = Question.find(params[:id])
    respond_to do |format|
      if @question.update_attributes(category: params[:question][:category], text: params[:question][:text])
        format.html { redirect_to(@question, notice: 'Question was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render action: 'edit' }
        format.xml  { render xml: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.xml
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to(:back) }
      format.xml  { head :ok }
    end
  end

  def setting
    @setting = YAML.load_file(Rails.root.join('config', 'event.yml'))
  end

  def save_setting
    @setting = { 'event' => { name: params[:name], date: params[:date],
                              passline: params[:passline], questions: params[:questions]} }
    File.write(Rails.root.join('config', 'event.yml'), @setting.to_yaml)
    redirect_to questions_setting_path, notice: 'Change saved.'
  end

  private

  def secure_params
    params.permit(:question, :text)
  end
end

app/helpers/questions_helper.rb
#--
# cyber_quiz
#
# A  Ruby application for enterprise online quiz management solution
#
# Developed by Yang Li, Kainan Zhang. Creative Common License
#
#++

module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= bootstrap_form_for(@question, layout: :horizontal, label_col: "col-md-2" ) do |f| %>
  <% if @question.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@question.errors.count, "error") %>
      prohibited this question from being saved:</h2>

    <ul>
      <% @question.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <%= f.text_field :category, control_col: "col-md-5"%>
  <%= f.text_area :text, rows:"10" %>
  <div class="text-right">
    <%= f.submit %>
  </div>

<% end %>

app/views/questions/_mod_menu.html.erb
<div class="col-sm-5 col-md-5">
  <div class="panel-group" id="accordion">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
            <span class="glyphicon glyphicon-th"></span>
            Menu</a>
        </h4>
      </div>
      <div id="collapseTwo" class="panel-collapse collapse ">
        <div class="panel-body">
          <table class="table">
            <tr>
              <td>
                <span class="glyphicon glyphicon-flash text-success"></span>
                <%= link_to 'New Question', new_question_path %>
              </td>
            </tr>
            <tr>
              <td>
                <span class="glyphicon glyphicon-flash text-success"></span>
                <a data-toggle="collapse" data-parent="#collapseTwo" href="#collapseThree">Questions List</a>
                <div id="collapseThree" class="panel-collapse collapse">
                  <div class="panel-body">
                    <table class="table">
                      <% Question.distinct.pluck(:category).each do |category| %>
                      <tr>
                        <td>
                          <span class="glyphicon glyphicon-pencil text-info"></span>
                          <%= link_to "#{category}", questions_list_path(category: category), method: :get %>
                        </td>
                      </tr>
                      <% end %>
                      <tr>
                        <td>
                          <span class="glyphicon glyphicon-cog text-info"></span>
                          <%= link_to "Questions Settings", questions_setting_path, method: :get %>
                        </td>
                      </tr>
                    </table>
                  </div>
                </div>
              </td>
            </tr>
            <tr>
              <td>
                <span class="glyphicon glyphicon-flash text-success"></span>
                <%= link_to 'Quiz Records', reporter_index_path%>
              </td>
            </tr>
            <tr>
              <td>
                <span class="glyphicon glyphicon-flash text-success"></span>
                <%= link_to 'Candidate Check', reporter_check_path(category: [""], eventid: [""])%>
              </td>
            </tr>
            <tr>
              <td>
                <span class="glyphicon glyphicon-flash text-success"></span>
                <%= link_to 'Trainers List', trainers_path%>
              </td>
            </tr>
            <tr>
              <td>
                <span class="glyphicon glyphicon-flash text-success"></span>
                <%= link_to 'Logo Setting', trainers_logo_path%>
              </td>
            </tr>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/questions/edit.html.erb
<h1>Editing question</h1>
<body>
<%= render 'form' %>
<%= link_to 'Show', @question %> |
<%= link_to 'Back', :back %>

<% content_for(:title) do %>
  Edit Question
<% end %>
</body>

app/views/questions/index.html.erb
<h1>Questions Manager</h1>

<div class='container'>
<%= render 'mod_menu' %>
</div>

<% content_for(:title) do %>
  All Questions
<% end %>

app/views/questions/list.html.erb
<h1>Listing questions</h1>

<p>Total: <%= @questions.size %></p>

<table class = "table table-bordered table-striped">
  <tr>
    <th class="col-md-1">ID </th>
    <th class="col-md-1">Category </th>
    <th class="col-md-4">Text</th>
    <th class="col-md-4">Choices</th>
    <th colspan="3"></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= question.id %> </td>
    <td><%= question.category %> </td>
    <td><%= question.text %></td>
    <td>
      <ul>
        <% question.choices.each do |choice| %>
          <li>
            <%= choice.text %>
            <% if choice.correct %> (Correct) <% end %>
          </li>
        <% end %>
      </ul>
    </td>
    <td><%= link_to 'Show', question %></td>
    <td><%= link_to 'Edit', edit_question_path(question) %></td>
    <td><%= button_to 'Delete', question_path(question.id), :method => :delete %></td>
  </tr>
<% end %>
</table>

<% content_for(:title) do %>
  All Questions
<% end %>

app/views/questions/new.html.erb
<script type="text/javascript">
label.required:after {
  content:" *";
}
</script>

<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

<% content_for(:title) do %>
  New Question
<% end %>

app/views/questions/setting.html.erb
<script>
$(document).ready(function() {
    $("#setting_form").validate({ // initialize the plugin
      rules: {
        questions: {
          required: true,
          min: 1
        },
        passline: {
          required: true,
          min: 0,
          max: 100
        }
      },
      messages: {
        passline: "Please enter a valid number",
        questions: "At least 1 question."
      },
      // Make sure the form is submitted to the destination defined in the "action" attribute of the form when valid
    });
    console.log($("#setting_form").valid());
});
</script>

<h1>Current Setting</h1>
<%= bootstrap_form_tag(url: '/questions/save_setting', layout: :horizontal, label_col: "col-md-4", html: {id: 'setting_form'}) do |f| %>
<%= f.text_field :name, label: "Event name", control_col: "col-md-4",
                 value: @setting['event'][:name], required: true%>
<%= f.date_select :date, label: "Dateline", control_col: "col-md-4",
                 value: @setting['event'][:date],required:true%>
<%= f.number_field :questions, label: "How many questions are in the test?", value: @setting['event'][:questions],
                    control_col: "col-md-4", required: true, help:'Number will not exceed the total amount.'%>
<%= f.number_field :passline, label: "What is the minimum score(percentage) to pass?", value: @setting['event'][:passline],
                    control_col: "col-md-4", required: true, help:'between 0 and 100'%>
<div class="text-right">
  <%= f.submit :save, id: 'submit'%>
</div>

<% end %>

app/views/questions/show.html.erb
<div class='container'>
  <h1>
    Questions Details
  </h1>
  <table class='table table-bordered'>
    <thead class="thead-default">
      <tr class="bg-info">
        <th class="col-md-2">Question</th>
        <th class="col-md-9"><%= @question.text %></th>
        <th class="col-md-1"></th>
      </tr>
      <% if @question.choices.empty? %>
      <tr>
        <td colspan="12">
          Please add choice to the question.
        </td>
      </tr>
    <% else
    @question.choices.each_with_index do |choice, index| %>
      <tr>
        <td>
          <%= index+1 %>
        </td>
        <td>
          <%= choice.text %>
          <% if choice.correct %>
          (Correct)
          <% end %>
        </td>
        <td>
          <%= form_tag({:controller => "choices", :action => "destroy"}) do %>
          <%= hidden_field_tag :question, @question.id %>
          <%= hidden_field_tag :choice, choice.id %>
          <%= submit_tag "Delete" %>
          <% end %>
        </td>
        <% end %>
        <% end %>
      </table>

      <h3>Add New Choice</h3>
      <%= form_tag({:controller => "choices", :action => "create"}, class: "form-horizontal") do %>
        <%= hidden_field_tag :question, @question.id %>
        <div class="form-group row">
          <label for="text" class="col-2 col-form-label">Choice</label>
          <div class="col-10">
            <%= text_area_tag :text, nil, size: "100x5"%>
          </div>
        </div>
        <div class="form-group">
          <%= check_box_tag :correct%>
          <%= label_tag :correct, "correct"%>
          <%= submit_tag "Create"%>
        </div>
      <% end %>

      <%= link_to 'Edit', edit_question_path(@question) %>|
      <%= link_to 'Back', new_question_path %>

      <% content_for(:title) do %>
      Question Details
      <% end %>
    </div>