config/routes.rb
Quizapp::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'users/list' => 'users#index'
    get 'users/report' => 'users#report'
    get 'users/:id' => 'users#show'
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users

  get 'trainers/logo' => 'trainers#logo', :via => :get
  resources :trainers
  get 'trainers/:id/crop' => 'trainers#crop'
  post 'trainers/:id/cropped_image' => 'trainers#cropped_image'
  get 'trainers/:id/remove_logo' => 'trainers#remove_logo'

  resources :documents, only: %i[index new create destroy]

  get 'documents/index'

  get 'documents/new'

  get 'documents/create'

  get 'documents/destroy'

  root 'home#page'

  get 'home/page'

  get 'home/support_contact'

  get 'home/about'

  get 'questions/list'
  get 'questions/setting' => 'questions#setting', :via => :get
  post 'questions/save_setting' => 'questions#save_setting', :via => :post
  resources :questions

  get 'quiz/index'

  post 'quiz/start'

  get 'quiz/question'

  post 'quiz/question'

  post 'quiz/answer'

  get 'quiz/result'

  post 'choices/create'

  post 'choices/destroy'

  post 'reporter/create'

  get 'reporter/index'

  get 'reporter/check'

  get 'reporter/list'

  post 'reporter/save'

  resource :candidates

  get 'candidates/synchronize'

  post 'candidates/refresh'

end

app/models/reporter.rb
class Reporter < ActiveRecord::Base
  def self.search(name, category)
    if name != '' && category != ''
        where('candidate LIKE ? and quiz_category = ?', "%#{name}%", "#{category}")
    elsif name == '' && category != ''
        where('quiz_category = ?', "#{category}")
    elsif name != '' && category == ''
        where('candidate LIKE ?', "%#{name}%")
    else
        all
    end
  end
end

app/controllers/reporter_controller.rb
#--
# cyber_quiz
#
# A  Ruby application for enterprise online quiz management solution
#
# Developed by Yang Li, Kainan Zhang. Creative Common License
#
#++

class ReporterController < ApplicationController

  before_action :authenticate_user!, except: [:create]
  before_action :init_reporter_env
  helper_method :sort_column, :sort_direction

  def init_reporter_env
    # @candidate_list = YAML.load_file(Rails.root.join('config','candidate_list.yml'))
    candidate_array = Candidate.all.order(:name).map { |c| [c['name'], [c['email'], c['status']]] }
    @candidate_list = {}
    candidate_array.each do |key, value|
      @candidate_list.merge!({key => value})
    end
  	@event = YAML.load_file(Rails.root.join('config','event.yml'))
  end

  def index
    if params[:category].nil?
      @records = Reporter.search(params[:name], '').paginate(page: params[:page], per_page: 15).order(sort_column + ' ' + sort_direction)
    else
      @records = Reporter.search(params[:name], params[:category][0]).paginate(page: params[:page], per_page: 15).order(sort_column + ' ' + sort_direction)
    end
  end

  def create
    @record = Reporter.new
    @record.candidate = params[:name][0]
    @record.candidate_email = @candidate_list[params[:name][0]][0]
    @record.quiz_eventid = @event['event'][:name]
    @record.quiz_category = params[:quiz_category]
    @record.quiz_score = params[:score]
    @record.save
    reset_session
    session.delete(session[:user_id])
    redirect_to root_url, notice: 'Record saved!'
  end

  def check
    category = params[:category][0]
    eventid = params[:eventid][0]
    @recorded_candidates = Reporter.where(quiz_category: category, quiz_eventid: eventid).distinct.pluck(:candidate)
    @recorded_candidates.each do |name|
      @candidate_list.delete(name)
    end
  end

  def save
    file_content = params[:file_tag]
    @file = Rails.root.join('config', 'candidate_list.yml')
    file = File.open(@file, 'w+')
    file.write(file_content)
    file.close
    redirect_to reporter_list_path, notice: 'The list file has been saved.'
  end

  def list
    @list_file = Rails.root.join('config', 'candidate_list.yml')
  end

  private

  def sort_column
    Reporter.column_names.include?(params[:sort]) ? params[:sort] : 'candidate'
  end

  def sort_direction
    %w(asc desc).include?(params[:direction]) ? params[:direction] : 'asc'
  end

end

app/helpers/reporter_helper.rb
#--
# cyber_quiz
#
# A  Ruby application for enterprise online quiz management solution
#
# Developed by Yang Li, Kainan Zhang. Creative Common License
#
#++


module ReporterHelper
  def init_reporter_env
  	#@candidate_list = YAML.load_file(Rails.root.join('config','candidate_list.yml'))
    @candidate_list = Candidate.pluck(:name, :email).to_h
    @event = YAML.load_file(Rails.root.join('config','event.yml'))
  end

  def check(category, eventid)
    init_reporter_env
    recorded_candidates = Reporter.where(quiz_category: category, quiz_eventid: eventid).distinct.pluck(:candidate_email).map {|x| x.downcase}
    puts "Recorded_candidates: #{recorded_candidates.inspect}"
    puts "Total record count: #{recorded_candidates.count}"
    return {} if recorded_candidates.nil?
    @candidate_list.each do |name,email|
      @candidate_list.delete(name) if recorded_candidates.include?(email.downcase)
    end
  end

end

app/views/reporter/check.html.erb
<script>
$(document).ready(function () {
  $('*:not(.bootstrap-select) > .selectpicker').selectpicker('refresh');
});

function toggle(source) {
    checkboxes = document.getElementsByName('email[]');
    for (var i = 0, n = checkboxes.length; i < n; i++) {
        checkboxes[i].checked = source.checked;
    }
};
</script>

<h1>Check Unrecorded Users</h1>

<%= form_tag({:controller => "reporter", :action => "check"}, :method => 'get') do %>
  	Category: <%= select(:category, nil, Question.distinct.pluck(:category), {:include_blank =>true},
  	 {:class => "selectpicker", "data-style" => "btn-default", required: true}) %>
     &nbsp;
    EventId: <%= select(:eventid, nil, Reporter.distinct.pluck(:quiz_eventid), {:include_blank =>true},
   	 {:class => "selectpicker", "data-style" => "btn-default", required: true}) %>
  	<%= submit_tag "Check", :class => "btn btn-default"%>
<% end %>
<hr class="style1">
<div class="table-responsive col-md-12 col-lg-12">
    <br/>
    <table class="table table-striped" style='width:1000px'>
        <tr>
            <th><%= sortable "candidate", "Candidate" %></th>
            <th>Email</th>
            <th>Status</th>
            <th><input type="checkbox" onClick="toggle(this)"> Notice All (<%=@candidate_list.size %>)</th>
        </tr>
    <% if @candidate_list.empty? %>
        <tr>
            <td colspan=8 align=center><%= "No Record To Show" %></td>
        </tr>
    <% else %>
        <% for candidate in @candidate_list do%>
        <tr>
            <td><%= candidate[0] %></td>
            <td><%= candidate[1][0] %></td>
            <td><%= if candidate[1][1]
                      'Active'
                    else
                      'Inactive'
                    end
               %></td>
            <td><%= check_box_tag 'email[]', candidate[1] %></td>
        <tr>
        <% end %>
    <% end %>
    </table>
</div>
<br/>
<div class="row"></div>
<div>
<%= link_to "Back", questions_path, class: "btn btn-default"%>&nbsp;
<%= link_to "Upload", reporter_list_path, class: "btn btn-warning"%>
</div>

app/views/reporter/index.html.erb
<h1>Quiz Records</h1>
<div align="left">
    <%= form_tag reporter_index_path, :method => 'get' do %>
    <p>
        <%= text_field_tag :name, params[:name], placeholder: 'Name'%> AND/OR
        <%= select(:category, nil, Question.distinct.pluck(:category), {:include_blank =>"Category"},
      	 {class: "select-style"}) %>
        <%= submit_tag "Search", :name => nil %>
    </p>
    <% end %>
</div>
<hr class="style1">
<div class="table-responsive col-md-12 col-lg-12">
    <table class="table table-striped" style='width:1000px'>
        <tr>
            <th><%= sortable "candidate", "Candidate" %></th>
            <th>Email</th>
            <th>Category</th>
            <th>Eventid</th>
            <th><%= sortable "quiz_score", "Score" %></th>
            <th><%= sortable "updated_at", "Date" %></th>
        </tr>
    <% if @records.empty? %>
        <tr>
            <td colspan=8 align=center><%= "No Record To Show" %></td>
        </tr>
    <% else %>
        <% for record in @records do%>
        <tr>
            <td><%= record.candidate %></td>
            <td><a href=mailto:<%= record.candidate_email %>><%= record.candidate_email %></a></td>
            <td><%= record.quiz_category %></td>
            <td><%= record.quiz_eventid %></td>
            <td><%= record.quiz_score %></td>
            <td><%= record.created_at %></td>
        <% end %>
    <% end %>
    </table>
</div>
<div class="flickr_pagination">
    <%= will_paginate @records %>
    <div class="page_info">
      <%= page_entries_info @records%>
    </div>
</div>
<%= link_to "Back", questions_path, class: "btn btn-default"%>

app/views/reporter/list.html.erb
<table class="table">
  <tr>
    <td>
      <div class="tab-content col-md-9 col-lg-9">
        <div>
          <% data = String.new %>
          <% map = File.open(@list_file, 'r+') %>
          <% map.each_line { |line|  data += line }; map.close%>
          <h4>Use file to synchronize candidate database
          </h4>
          <p>
            <%= form_tag "/reporter/save" do %>
            <%= text_area_tag :file_tag, data, rows: 22, cols: 80, placeholder: "John, Doe: johndoe@123.com" %>
            <br>
            <div>
              <button class="btn btn-default" type="submit">Save before Synchronize</button>
              <%= link_to "Synchronize", candidates_synchronize_path, class: "btn btn-warning", data: { confirm: 'Synchronize?'}  %>
            </div>
            <% end %>
          </p>
        </div>
      </div>
    </td>
  </tr>
</table>