config/routes.rb
Quizapp::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'users/list' => 'users#index'
    get 'users/report' => 'users#report'
    get 'users/:id' => 'users#show'
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users

  get 'trainers/logo' => 'trainers#logo', :via => :get
  resources :trainers
  get 'trainers/:id/crop' => 'trainers#crop'
  post 'trainers/:id/cropped_image' => 'trainers#cropped_image'
  get 'trainers/:id/remove_logo' => 'trainers#remove_logo'

  resources :documents, only: %i[index new create destroy]

  get 'documents/index'

  get 'documents/new'

  get 'documents/create'

  get 'documents/destroy'

  root 'home#page'

  get 'home/page'

  get 'home/support_contact'

  get 'home/about'

  get 'questions/list'
  get 'questions/setting' => 'questions#setting', :via => :get
  post 'questions/save_setting' => 'questions#save_setting', :via => :post
  resources :questions

  get 'quiz/index'

  post 'quiz/start'

  get 'quiz/question'

  post 'quiz/question'

  post 'quiz/answer'

  get 'quiz/result'

  post 'choices/create'

  post 'choices/destroy'

  post 'reporter/create'

  get 'reporter/index'

  get 'reporter/check'

  get 'reporter/list'

  post 'reporter/save'

  resource :candidates

  get 'candidates/synchronize'

  post 'candidates/refresh'

end

app/models/trainer.rb
class Trainer < ActiveRecord::Base
  mount_uploader :logo, ImageUploader
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h 
end

app/controllers/trainers_controller.rb
#--
# cyber_quiz
#
# A  Ruby application for enterprise online quiz management solution
#
# Developed by Yang Li, Kainan Zhang. Creative Common License
#
#++


class TrainersController < ApplicationController
  before_action :set_trainer, only: [:show, :edit, :update, :destroy, :crop, :cropped_image, :remove_logo]

  # GET /trainers
  # GET /trainers.json
  def index
    @trainers = Trainer.all
  end

  # GET /trainers/1
  # GET /trainers/1.json
  def show
  end

  # GET /trainers/new
  def new
    @trainer = Trainer.new
  end

  # GET /trainers/1/edit
  def edit
  end

  # POST /trainers
  # POST /trainers.json
  def create
    @trainer = Trainer.new(trainer_params)

    respond_to do |format|
      if @trainer.save
        format.html { redirect_to @trainer, notice: 'Trainer was successfully created.' }
        format.json { render :show, status: :created, location: @trainer }
      else
        format.html { render :new }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainers/1
  # PATCH/PUT /trainers/1.json
  def update
    respond_to do |format|
      if trainer_params[:logo].nil?
        if @trainer.update(trainer_params)
          format.html { redirect_to @trainer, notice: 'Trainer was successfully updated.' }
          format.json { render :show, status: :ok, location: @trainer }
        else
          format.html { render :edit }
          format.json { render json: @trainer.errors, status: :unprocessable_entity }
        end
      else
        if @trainer.update(trainer_params)
          format.html { redirect_to :back, notice: 'Trainer was successfully updated.' }
          format.json { render :show, status: :ok, location: @trainer }
        else
          format.html { render :edit }
          format.json { render json: @trainer.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /trainers/1
  # DELETE /trainers/1.json
  def destroy
    @trainer.destroy
    respond_to do |format|
      format.html { redirect_to trainers_url, notice: 'Trainer was successfully destroyed.' }
      format.json { head :no_content }
    end
    FileUtils.rm('public/uploads/trainer/logo_crop.png') if File.exist?('public/uploads/trainer/logo_crop.png')
  end

  def logo
    @trainer = Trainer.first
    if @trainer.nil?
      redirect_to new_trainer_path, notice: 'Please create a trainer first.'
    end
  end

  def crop
    @path1 = File.join Rails.root, 'public/uploads/trainer/logo.png'
    @path2 = File.join Rails.root, 'public/uploads/trainer/logo_crop.png'
    FileUtils.cp @path1, @path2
  end

  def cropped_image
    image = MiniMagick::Image.open(params[:path])
    crop_params = "#{params[:trainer][:crop_w]}x#{params[:trainer][:crop_h]}+#{params[:trainer][:crop_x]}+#{params[:trainer][:crop_y]}"
    image.crop(crop_params)
    image.write (params[:path])
    redirect_to trainers_logo_path
  end

  def remove_logo
    @trainer.remove_logo!
    @trainer.save
    FileUtils.rm('public/uploads/trainer/logo_crop.png') if File.exists?('public/uploads/trainer/logo_crop.png')
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trainer
      @trainer = Trainer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trainer_params
      params.require(:trainer).permit(:name, :email, :phone, :description, :logo)
    end
end

app/helpers/trainers_helper.rb
#--
# cyber_quiz
#
# A  Ruby application for enterprise online quiz management solution
#
# Developed by Yang Li, Kainan Zhang. Creative Common License
#
#++


module TrainersHelper
end

app/views/trainers/_form.html.erb
<%= form_for @trainer, html: { multipart: true } do |f| %>
  <% if @trainer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trainer.errors.count, "error") %> prohibited this trainer from being saved:</h2>

      <ul>
      <% @trainer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

<%= bootstrap_form_for(@trainer, html: {multipart: true}) do |f| %>
    <%= f.text_field :name, required: true%>
    <%= f.email_field :email, required: true%>
    <%= f.phone_field :phone, required: true%>
    <%= f.text_area :description, rows: "2" , required: true%>
    <%= f.submit :submit %>
<% end %>

app/views/trainers/crop.html.erb
<meta http-equiv="Cache-control" content="no-cache">
<%= stylesheet_link_tag "Jcrop.css" %>
<%= javascript_include_tag 'Jcrop.js' %>
<script type="text/javascript">
    $(function () {
        $('#cropbox').Jcrop({
            onChange: update_crop,
            onSelect: update_crop,
            bgColor : '',
            boxWidth: 500, boxHeight: 500,
        });
    });

    function update_crop(coords) {
        $('#crop_x').val(coords.x);
        $('#crop_y').val(coords.y);
        $('#crop_w').val(coords.w);
        $('#crop_h').val(coords.h);
    }
</script>

<h3>
    Crop your logo
</h3>
<%= image_tag('/uploads/trainer/logo_crop.png?'+ DateTime.now.strftime('%s'), id: "cropbox")%>
<%= form_for @trainer, url:{action: "cropped_image", path: URI.parse(URI.encode(@path2))}, method: :post do |form| %>
<% for attribute in [:crop_x, :crop_y, :crop_w, :crop_h] %>
<%= form.hidden_field attribute, :id => attribute %>
<% end %>
<p><%= form.submit "Crop" %></p>
<% end %>

<span class="glyphicon glyphicon-step-backward"><%=link_to 'Back', url_for(trainers_logo_path) %></span>

app/views/trainers/edit.html.erb
<h1>Editing Trainer</h1>

<%= render 'form' %>

</br>
<%= link_to 'Show', @trainer %> |
<%= link_to 'Back', trainers_path %>

app/views/trainers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Trainers</h1>

<table class = "table talbe-boarded table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trainers.each do |trainer| %>
      <tr>
        <td><%= trainer.name %></td>
        <td><%= trainer.email %></td>
        <td><%= trainer.phone %></td>
        <td><%= trainer.description %></td>
        <td><%= link_to 'Show', trainer %></td>
        <td><%= link_to 'Edit', edit_trainer_path(trainer) %></td>
        <td><%= link_to 'Destroy', trainer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trainer', new_trainer_path %>

app/views/trainers/logo.html.erb
<meta http-equiv="Cache-control" content="no-cache">
<script>
    function Crop() {
        var w = 1000;
        var h = 700;
        // Fixes dual-screen position Most browsers Firefox
        var dualScreenLeft = window.screenLeft != undefined
            ? window.screenLeft
            : screen.left;
        var dualScreenTop = window.screenTop != undefined
            ? window.screenTop
            : screen.top;
        width = window.innerWidth
            ? window.innerWidth
            : document.documentElement.clientWidth
                ? document.documentElement.clientWidth
                : screen.width;
        height = window.innerHeight
            ? window.innerHeight
            : document.documentElement.clientHeight
                ? document.documentElement.clientHeight
                : screen.height;

        //var image = document.getElementById('logo');
        var id = document.getElementById('id').value;
        var url = "/trainers/"+id+"/crop";
        //var url = "/go_uploads/show?image="+
        var left = ((width / 2) - (w / 2)) + dualScreenLeft;
        var top = ((height / 2) - (h / 2)) + dualScreenTop;
        var newWindow = window.open(url, 'CROP', 'width=' + w + ', height=' + h + ', top=' + top + ', left=' + left);

        // Puts focus on the newWindow
        if (window.focus) {
            newWindow.focus();
        }
    }
</script>
<h1>Upload Your Logo </h1>
<div class="container">
<%= bootstrap_form_for(@trainer, html: {multipart: true}) do |f| %>
<%= f.hidden_field :id, id:'id'%>
<%= f.file_field :logo, help: 'png format preferred.', required: true%>
    <% if f.object.logo? %>
    <%= image_tag(f.object.logo.url+'?'+DateTime.now.strftime('%s'), id: 'logo', size: '600x240', onclick: 'Crop()', style: ' cursor: pointer;', title: 'click_to_crop')%>
    </br>
    <%= link_to 'Remove Logo', action: "remove_logo", id: f.object.id%>
    <% end %>
</br>
    <%= f.submit :submit %>
<% end %>
</div>

app/views/trainers/new.html.erb
<h1>New Trainer</h1>

<%= render 'form' %>

<%= link_to 'Back', trainers_path %>

app/views/trainers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @trainer.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @trainer.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @trainer.phone %>
</p>

<p>
  <strong>Description:</strong>
  <%= @trainer.description %>
</p>

<%= link_to 'Edit', edit_trainer_path(@trainer) %> |
<%= link_to 'Back', trainers_path %>