config/routes.rb
Quizapp::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'users/list' => 'users#index'
    get 'users/report' => 'users#report'
    get 'users/:id' => 'users#show'
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users

  get 'trainers/logo' => 'trainers#logo', :via => :get
  resources :trainers
  get 'trainers/:id/crop' => 'trainers#crop'
  post 'trainers/:id/cropped_image' => 'trainers#cropped_image'
  get 'trainers/:id/remove_logo' => 'trainers#remove_logo'

  resources :documents, only: %i[index new create destroy]

  get 'documents/index'

  get 'documents/new'

  get 'documents/create'

  get 'documents/destroy'

  root 'home#page'

  get 'home/page'

  get 'home/support_contact'

  get 'home/about'

  get 'questions/list'
  get 'questions/setting' => 'questions#setting', :via => :get
  post 'questions/save_setting' => 'questions#save_setting', :via => :post
  resources :questions

  get 'quiz/index'

  post 'quiz/start'

  get 'quiz/question'

  post 'quiz/question'

  post 'quiz/answer'

  get 'quiz/result'

  post 'choices/create'

  post 'choices/destroy'

  post 'reporter/create'

  get 'reporter/index'

  get 'reporter/check'

  get 'reporter/list'

  post 'reporter/save'

  resource :candidates

  get 'candidates/synchronize'

  post 'candidates/refresh'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The Quiz Online by <%= link_to "Trainers Team", home_support_contact_url%>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", home_about_url%></li>
      <% unless Trainer.all.pluck(:email).empty? %>
      <li><a href="mailto:<%= Trainer.all.pluck(:email)[0]%>">Contact</a></li>
      <% end %>
    </ul>
  </nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
 <!-- 	<% flash.each do |key, value| %>
  	 <div class="alert alert-info alert-dismissible fade in"><%= value %></div>
  	<% end %>
-->
  <% unless flash.blank? %>
<div class='row'>
  <div class='col-sm-12'>
    <div id='flash'>
      <% flash.each do |key, value| %>
        <div class='flash alert-temp alert alert-dismissible fade in alert-<%= key == 'notice' ? 'info' : 'danger'%>'>
          <button type='button' class='close' data-dismiss='alert' aria-label='Close'>
            <span aria-hidden='true'>&times;</span>
          </button>
          <%= value %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
          <%= image_tag('/uploads/trainer/default.png'+'?'+DateTime.now.strftime('%s'), size: "150x60", id: "logo")%>
          <% if File.exist?('public/uploads/trainer/logo_crop.png') %>
            <%= image_tag('/uploads/trainer/logo_crop.png'+'?'+DateTime.now.strftime('%s'), size: "150x60", id: "logo")%>
          <%elsif File.exist?('public/uploads/trainer/logo.png')%>
            <%= image_tag('/uploads/trainer/logo.png'+'?'+DateTime.now.strftime('%s'), size: "150x60", id: "logo")%>
          <% else %>
          <% end %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Docs",  documents_index_path %></li>
            <li><%= link_to "Admin", questions_path%></li>
            <% if user_signed_in? %>
              <li><%= link_to('Logoff', destroy_user_session_path, :method => :delete) %></li>
            <% else %>
              <li><%= link_to('Logon', new_user_session_path)  %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>

  <%= debug(params)if Rails.env.development? %>
  <%= params.inspect if Rails.env.development? %>

</html>